name: "Add Issues to Project"
description: "Adds issues from a specified repository to a specified GitHub Project."
author: "MiguelRodo"

branding:
  icon: "list"
  color: "blue"

inputs:
  project_name:
    description: "Project name. Defaults to repository name."
    required: false
  project_owner:
    description: "Project owner. Defaults to repository owner."
    required: false
  is_project_owner_org:
    description: "Whether the project owner is an organization. Defaults to `false`."
    required: false
    default: "false"
  source_repo_name:
    description: "Repository name. Defaults to current repository."
    required: false
  source_repo_owner:
    description: "Repository owner. Defaults to current GitHub user."
    required: false
  ADD_ISSUES_TO_PROJECT_TOKEN:
    description: "GitHub token with correct access for accessing issues and writing to projects"
    required: true

outputs:
  issues_added:
    description: "Number of issues that were newly added to the project."
    value: ${{ steps.add-issues.outputs.issues_added }}

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up GitHub CLI and jq
      shell: bash
      run: |
        sudo apt update -y
        sudo apt install -y gh jq

        echo "GitHub CLI version: $(gh --version)"
        echo "jq version: $(jq --version)"

    - name: Install gh-projects extension
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.ADD_ISSUES_TO_PROJECT_TOKEN }}
      run: gh extension install github/gh-projects

    - name: Sync project issues
      id: add-issues
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.ADD_ISSUES_TO_PROJECT_TOKEN }}
        PROJECT_NAME: ${{ inputs.project_name }}
        PROJECT_OWNER: ${{ inputs.project_owner }}
        IS_PROJECT_OWNER_ORG: ${{ inputs.is_project_owner_org }}
        SOURCE_REPO_NAME: ${{ inputs.source_repo_name }}
        SOURCE_REPO_OWNER: ${{ inputs.source_repo_owner }}
        CURRENT_USER: ${{ github.actor }}
      run: "$GITHUB_ACTION_PATH/../scripts/add-issues-to-project.sh"
